# Generated by Django 3.2.14 on 2022-07-23 22:45

from django.db import migrations, models
import phone_field.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdNum', models.CharField(max_length=100, verbose_name='Numero de identificación')),
                ('IdType', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjeria')], max_length=100, verbose_name='Tipo de identificacón')),
                ('Names', models.CharField(max_length=100, verbose_name='Nombres del cliente')),
                ('LastNames', models.CharField(max_length=100, verbose_name='Apellidos del cliente')),
                ('Cellphone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numero de celular')),
                ('Phone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Numero de telefono')),
                ('Email', models.EmailField(max_length=200, verbose_name='Correo')),
                ('Title', models.CharField(max_length=200, verbose_name='Titulo del PQR')),
                ('TicketType', models.CharField(max_length=10, verbose_name='Tipo de Ticket')),
                ('Description', models.TextField(max_length=1000, verbose_name='Descripción del Ticket')),
                ('Status', models.CharField(choices=[('abierto', 'abierto'), ('cerrado', 'cerrado')], max_length=7, verbose_name='Estado del Ticket')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
    ]
