# Generated by Django 3.2.14 on 2022-07-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PQR', '0003_alter_pqr_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqr',
            options={'verbose_name_plural': 'PQR'},
        ),
        migrations.AlterModelTable(
            name='pqr',
            table='PQR',
        ),
    ]
